### PR TITLE
Frontend: Beautify frontend UI

### PR DESCRIPTION
**Pull request by Tan-Jia-Rong**
Remaining Things not done:
1. Cant really see the background issue on macbook might need to double check on @ekweirui windows to validate and try fix.

Things done:
1. Update table for better UI
2. Snaps matching options to top when screen is small

image

3. Fix fixed position profile button (see how when scroll down not over there)
image

### CODE REVIEW

**Comment by kenvynKwek** [comment]
snapping/resizing & top-right user icon looks great !

hmm on my windows machine the overflow is still there, will help to fix

image

**Comment by thedesalizes** [comment]
Minor issue where the snapping of matching options to adapt to screen size causes question table to refresh. Backend is called  every time this happens. Is it possible to make this only happen once(when the page is first loaded)?

**Comment by Tan-Jia-Rong** [comment]
@thedesalizes The reason why this happen is caused useEffect was used at the `QuestionPageView` to rerender the question table in a certain format. I am able to let it refresh only once. However, it does not conform to what I have in mind... But I think it still looks okay so i have editted it as such :)

**Review by ekweirui — APPROVED** [review]
LGTM! I will test it later alongside #73. Thanks for beautifying our frontend to improve our users overall UX! 💯

**Pull request merged**
